version: "3.3"
services:
  logstash_udp:
    container_name: logstash_udp
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./docker/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./docker/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./docker/logstash/patterns:/opt/logstash/patterns
    networks:
      plt13-containers_plt13:
        ipv4_address: 172.22.0.57
    ports:
      - "5044:5044/udp"
      - "9600:9600"
    env_file:
      - .env
networks:
  plt13-containers_plt13:
    external: true